name = "Magpie"
uuid = "f9571e17-2ade-4075-950a-6046adfb08e9"
authors = ["Prakrut Chaubal <prakrutchaubal@gmail.com> and contributors"]
version = "1.0.0-DEV"

[compat]
Aqua = "0.8.13"
JuliaFormatter = "1.0, 2.1"
Test = "1.6"
julia = "1.6.7"

[extras]
Aqua = "4c88cf16-eb10-579e-8560-4a9242c79595"
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"
JuliaFormatter = "98e50ef6-434e-11e9-1051-2b60c6c9e899"

[targets]
test = ["Aqua", "Test"]
